### ISSUE TITLE
Certificate issue 

### ISSUE THREAD

**Issue by alekhyachowdury** [lucas-matt/auto-tracing-webhook#4] opened 2020-07-22 17:25 UTC
Hi
We are getting the below issue while trying to set up Jaeger in kubernetes. 

"Internal error occurred: failed calling webhook "auto-tracing-mutating-webhook.default.svc.cluster.local": Post https://auto-tracing-mutating-webhook.default.svc:443/decorate?timeout=30s: x509: certificate has expired or is not yet valid "

It did work couple of times but started failing recently. Kindly help

Thanks in advance

**Comment by sundar-cs** [comment] 2020-09-13 10:53
Hi, 

We have the same issue. It used to work earlier couple of months back but now it stopped working and kubectl logs shows the same error as above.

I pasted the caBundle from webhook.yaml into a file and looked at the endDate and startDate, and they seem to be fine:
base64 -d webHook-caBundle | openssl x509 -enddate -noout
notAfter=Nov  3 14:05:14 2047 GMT

base64 -d webHook-caBundle | openssl x509 -startdate -noout
notBefore=Jun 17 14:05:14 2020 GMT

Looks like issue #1, #2, #3 were also relating to the same problem and as per the resolution it got fixed by extending the expiry date to 10K more days (which translates to around 30 years as confirmed by endDate above).
So now as the endDate is actually valid why it would it still result in **x509: certificate has expired or is not yet valid** error ?
Is it possible that the Kubernetes Api Server is giving a wrong error and if so how can we go about fixing this ?

Thanks a lot.

**Comment by aravindarc** [comment] 2020-09-16 00:09
@lucas-matt @alekhyachowdury @sundar-cs 
Hi,

I am facing the same issue. 

It is not an issue with Kube API Server, @lucas-matt seems to have either not bundled the keys properly while building the docker image, or else has not updated cert in the cabundle in webhook.yml. 

I cloned this repository, generated new keys, updated the cert in webhook.yml and built the docker image straight into the minikube docker daemon and used that image to deploy, it is working fine.

Thanks @lucas-matt for the excellent work.

**Comment by notmattlucas** [comment] 2020-09-16 15:03
Hi, 

I had updated the cert in the caBundle, but not the other cert in the docker image (so still timed out after a month).

a2d5152ef62c7aed72394921ab53cd8e1d9a7f05
450ab8df099d38e5a994ad1bcb98b65c107c69ba

Corrected now.

Thanks

**Closed as completed** 2020-09-16 15:04 UTC

**Comment by sundar-cs** [comment] 2020-09-20 16:47
Thank you all.
The certificate issue is resolved but why do I see these errors in kubectl logs (for service-a etc):

Installing new rule: io.opentracing.contrib.specialagent.rule.thread.ThreadAgentRule
Allowing instrumentation with "thread" due to "fingerprint.bin match" for:
file:/tmp/opentracing-specialagent4718381146378809422/META-INF/plugins/thread-1.5.0.jar

>>>>>>>>>>>>>>>>>>>>> Loaded AgentRule(s) <<<<<<<<<<<<<<<<<<<<<<


  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.6.RELEASE)

Disallowing instrumentation with "spring:messaging" due to "fingerprint.bin mismatch" errors:
 MISSING org.springframework.messaging.support.MessageBuilder,
 MISSING org.springframework.integration.context.ExpressionCapable,


And curl fails with http status 500.

Please let me know what's missing here ...
(the same behavior is observed with git clone and newly built docker image too)

**Comment by notmattlucas** [comment] 2020-09-20 18:15
Hi @sundar-cs - you should be able to just ignore those fingerprint mismatch warnings for the purpose of the demo. It uses a dynamic attach of the open-tracing jar, so is basically classpath scanning to see what it can instrument. It fails on the spring-messaging part specifically, but that shouldn't impact other parts that can be instrumented, and as we aren't using JMS etc here, it shouldn't have any impact at all.

The 500 is probably caused because the upstream API being proxied by the demo (http://worldclockapi.com/api/json/gmt/now) is down. You can change this upstream to any other endpoint you like by editing the [deployment.yml ](https://raw.githubusercontent.com/lucas-matt/pass-the-buck/master/deployment.yml) and setting the UPSTREAM of service-c to be whatever you like.

Although assuming this is the case, it may be an even more valuable demonstration of the usefulness of OpenTracing because the spans will still show up in Jaeger, and you'll be able to see where the issue is originating.

HTH

**Comment by sundar-cs** [comment] 2020-09-21 10:35
Thanks a bunch.
Yes Jaeger traces are showing up well and so we're fine in reality.
Very much agree that this serendipitous issue in fact demonstrates the value of auto-tracing to an even higher degree.

Really appreciate your help and quick response, please go ahead and close it again, thanks so much.

**Comment by notmattlucas** [comment] 2020-09-21 14:41
@sundar-cs great!

Thanks for the feedback. Glad it's all working for you.

All the best

**Comment by aravindarc** [comment] 2020-09-21 14:58
@sundar-cs @lucas-matt 
If you want to remove the fingerprint mismatch warnings, kindly update the javaspecial agent jar in the sidecar, it worked for me.
